name: config-server CI

on:
  push:
    branches: [ dev ]
    paths:
      - "config-server/**"
  pull_request:
    branches: [ dev ]
    paths:
      - "config-server/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Build with Gradle
        working-directory: ./config-server
        run: ./gradlew clean build

      - name: Docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/config-server:${{ github.sha }} ./config-server

      - name: Docker push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/config-server:${{ github.sha }}
