apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: msa
spec:
  type: NodePort
  selector:
    app: discovery-server
  ports:
    - name: http
      port: 8761        # 클러스터 내부 포트
      targetPort: 8761  # 컨테이너 내부 포트
      nodePort: 30061   # 외부에서 접근할 포트 (원하는 값으로 변경 가능)
